name: Android arm64-v8a Build

on: [push, pull_request]

env:
  ANDROID_NDK: ${{ github.workspace }}/android-ndk-r25b
  BUILD_DIR: build_android
  INSTALL_DIR: install_android

jobs:
  android-build:
    steps:
      - uses: actions/checkout@v4

      - name: Setup NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip android-ndk-r25b-linux.zip -d ${{ github.workspace }}
          echo "${{ env.ANDROID_NDK }}/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH

      - name: Build OpenSSL
        run: |
          git config --global http.sslVerify "false"
          git clone https://github.com/openssl/openssl.git
          cd openssl
          git checkout e04bd3433fd84e1861bf258ea37928d9845e6a86
          ./Configure --prefix=${{ github.workspace }}/openssl-android android-arm64 -D__ANDROID_API__=24
          make -j8
          make install

      - name: Verify OpenSSL
        run: |
          ls ${{ github.workspace }}/openssl-android/lib/libssl.so
          ls ${{ github.workspace }}/openssl-android/include/openssl
